#!/bin/bash

export JDK_HOME=/usr/lib/jvm/java-1.7.0

# Compile client-side packages
pushd prototype
    ./setup.sh

    SETUP_EXIT=$?
popd

if [ SETUP_EXIT != "0" ]; then
    exit 1
fi


# Build with SBT
/usr/lib/jvm/java-1.7.0/bin/java \
  -XX:+CMSClassUnloadingEnabled -Xmx2g -XX:MaxPermSize=350m -XX:+UseCompressedOops  \
  -Dbuild.number="$BUILD_NUMBER" -Dbuild.vcs.number="$BUILD_VCS_NUMBER" -Dbuild.vcs.branch="$BUILD_VCS_BRANCH" \
  -Dsbt.log.noformat=true -jar sbt-launch.jar "$@" < /dev/null

SBT_EXIT=$?

if [ $SBT_EXIT == "0" ]; then
    exit 0
else
    exit 1
fi