include "application"

#api.url="http://workflow-backend.local.dev-gutools.co.uk/api"
#api.url="http://localhost:9095/api"
api.url="http://host.docker.internal:9095/api"
google.tracking.id=""
capi.preview.iamUrl="https://iam-preview.content.code.dev-guardianapis.com"
capi.preview.role="arn:aws:iam::308506855511:role/content-api-proxy-iam-preview-CODE-WorkflowRole-IUTDWP8Q58VW"
webpush.publicKey="BLGkDff03GoV484Gf1kFKBgk88CFefGQuXQov3Xz8ireHo-3ZZk3VaHUl6KtGt7DZH1-DcZ2N_FBQTIz8FvpWac"
webpush.privateKey="3NYfWlVU-Ql345F0JU_m3xmXTYb_qplqAm3NEkwurEE"
api.sharedsecret="461ddd6c-d600-4ede-87ca-4f702249a583"

security.cors.allowedOrigins=integration-tests.local.dev-gutools.co.uk
