name: Snyk

on:
    schedule:
        - cron: "0 6 * * *"
    push:
        # branches:
        #     - main
    workflow_dispatch:

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@add-generic-snyk-workflow
    with:
      DEBUG: "true"
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
