name: Snyk

on:
    schedule:
        - cron: "0 6 * * *"
    push:
        # branches:
        #     - main
    workflow_dispatch:

jobs:
  security:
    uses: guardian/workflow-frontend/.github/workflows/test.yml@add-snyk-workflow
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
